import Head from 'next/head'
import Image from 'next/image'
import { Inter } from '@next/font/google'
import styles from '@/styles/Home.module.css'

const inter = Inter({ subsets: ['latin'] })

export default function Home() {
  return (
    <>
      <Head>
        <title>Web3 Dapp</title>
        <meta name="description" content="Generated by create next app" />
        <meta name="viewport" content="width=device-width, initial-scale=1" />
        <link rel="icon" href="/favicon.ico" />
      </Head>
      <header>
        <img alt="logo"></img>
        <nav>
          <ul>
            <li>Tokens</li>
            <li>NFTs</li>
            <li>Live Chat</li>
            <li>Signout/Login</li>
          </ul>
        </nav>
        <h1>Dapp</h1>
      </header>
      <main className={styles.main}>
                
      </main>
    </>
  )
}
